[package]
name = "ts-model"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
ts-derive.workspace = true
dotenvy.workspace = true
